# Generated by Django 3.2 on 2021-04-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contracte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.TextField()),
                ('denominacio', models.TextField()),
                ('codi_expedient', models.TextField()),
                ('objecte', models.TextField()),
                ('pressupost', models.FloatField()),
                ('valor_estimat', models.FloatField()),
                ('lloc_execucio', models.TextField()),
                ('duracio', models.TextField()),
                ('termini_presentacio_instancies', models.DateField()),
                ('tipus', models.TextField()),
                ('subtipus', models.TextField()),
            ],
        ),
    ]
